services:
  api:
    build: .
    container_name: b1k5-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret123
      - DB_NAME=b1k5_api
      - DB_DRIVER=postgres
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: b1k5-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: b1k5_api
    ports:
      - "5433:5432" # avoid conflict with local Postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: b1k5-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pg_data:
